language: c

if: NOT tag =~ .*-prerelease$

addons:
  apt:
    packages:
      - cmake
      - cmake-data

before_install:
   - '[ ! -f .travis.d/before_install ] || source .travis.d/before_install'

# install:
#    - '[ ! -f .travis.d/install ] || source .travis.d/install'
#
# before_script:
#    - '[ ! -f .travis.d/before_script ] || source .travis.d/before_script'
#

script:
   - '[ ! -f .travis.d/script ] || source .travis.d/script'

# before_cache:
#    - '[ ! -f .travis.d/before_cache ] || source .travis.d/before_cache'
#
# after_success:
#    - '[ ! -f .travis.d/after_success ] || source .travis.d/after_success'
#
# after_failure:
#    - '[ ! -f .travis.d/after_failure ] || source .travis.d/after_failure'
#
# before_deploy:
#    - '[ ! -f .travis.d/before_deploy ] || source .travis.d/before_deploy'
#
# after_deploy:
#    - '[ ! -f .travis.d/after_deploy ] || source .travis.d/after_deploy'
#
# after_script:
#    - '[ ! -f .travis.d/after_script ] || source .travis.d/after_script'
